# Generated by Django 4.0 on 2022-01-17 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100, unique=True)),
                ('host_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('image_file', models.FileField(blank=True, upload_to='persons/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Violence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(upload_to='violences')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveillance.camera')),
                ('involved_persons', models.ManyToManyField(blank=True, to='surveillance.Person')),
            ],
        ),
    ]
